server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noodle?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 启动时创建表，开发测试用，生产可改成 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
